name: DonateGUI
api: 5.0.0
version: 1.0.0
main: ClickedTran\DonateGUI\DonateGUI
virion: ["InvMenu"]

authors:
- VicthorCaius (Coder)
- ClickedTran (Idea maker)

permissions:
  donategui.command:
    default: true
